export module Core {
  export declare enum AccountTransactionRetrieval {
    get_acct_has_ordered_sku = "get_acct_has_ordered_sku",
    get_acct_service_outage_credit = "get_acct_service_outage_credit",
    get_acct_writeoff_or_disputes = "get_acct_writeoff_or_disputes",
    get_extended_transaction_info = "get_extended_transaction_info",
    get_family_trans_history = "get_family_trans_history",
    get_invoice_details = "get_invoice_details",
    get_invoices_to_writeoff_or_dispute = "get_invoices_to_writeoff_or_dispute",
    get_order = "get_order",
    get_payment_application_dtls = "get_payment_application_dtls",
    get_payment_applications = "get_payment_applications",
    get_payments_on_invoice = "get_payments_on_invoice",
    get_paypal_avs_status = "get_paypal_avs_status",
    get_pending_invoice_no = "get_pending_invoice_no",
    get_refund_details = "get_refund_details",
    get_refundable_payments = "get_refundable_payments",
    get_reversible_authorizations = "get_reversible_authorizations",
    get_reversible_invs_by_payment = "get_reversible_invs_by_payment",
    get_standing_order = "get_standing_order",
    get_standing_order_hist = "get_standing_order_hist",
    get_standing_order_items = "get_standing_order_items",
    get_unapplied_service_credits = "get_unapplied_service_credits",
    get_writeoff_details = "get_writeoff_details",
    issue_refund_to_acct = "issue_refund_to_acct",
    reverse_authorized_electronic_payment = "reverse_authorized_electronic_payment",
    update_refund_check_no = "update_refund_check_no",
    validate_acct_fraud_scoringvalidate_payment_information = "validate_acct_fraud_scoringvalidate_payment_information"
  }
  
  export declare enum AccountTransactionModification {
    apply_cash_credit = "apply_cash_credit",
    apply_coupon_to_acct = "apply_coupon_to_acct",
    apply_service_credit = "apply_service_credit",
    assign_custom_acct_rates = "assign_custom_acct_rates",
    cancel_acct_multiplan_contract = "cancel_acct_multiplan_contract",
    cancel_acct_universal_contract = "cancel_acct_universal_contract",
    cancel_order = "cancel_order",
    cancel_queued_service_plan = "cancel_queued_service_plan",
    cancel_recurring_credits = "cancel_recurring_credits",
    cancel_standing_order = "cancel_standing_order",
    cancel_unapplied_svce_credits = "cancel_unapplied_svce_credits",
    cancel_unconsumed_credit = "cancel_unconsumed_credit",
    create_advanced_service_credit = "create_advanced_service_credit",
    create_writeoff_or_dispute = "create_writeoff_or_dispute",
    disable_standing_usage = "disable_standing_usage",
    discard_usage = "discard_usage",
    record_standing_order = "record_standing_order",
    reinstate_transaction = "reinstate_transaction",
    save_paypal_bill_agreement = "save_paypal_bill_agreement",
    settle_dispute_hold = "settle_dispute_hold",
    transfer_account_balance = "transfer_account_balance",
    update_acct_billing_contact = "update_acct_billing_contact",
    void_transaction = "void_transaction"
  }
  
  export declare enum AccountTransactionCreation {
    authorize_3dsecure = "authorize_3dsecure",
    authorize_electronic_payment = "authorize_electronic_payment",
    bulk_record_usage = "bulk_record_usage",
    collect_from_account = "collect_from_account",
    create_order = "create_order",
    create_order_with_plans = "create_order_with_plans",
    gen_invoice = "gen_invoice",
    init_paypal_bill_agreement = "init_paypal_bill_agreement",
    manage_pending_invoice = "manage_pending_invoice",
    move_payment = "move_payment",
    record_external_payment = "record_external_payment",
    record_mandate_approval = "record_mandate_approval",
    record_out_going_payment = "record_out_going_payment",
    record_standing_usage = "record_standing_usage",
    record_usage = "record_usage",
    settle_account_balance = "settle_account_balance",
    update_acct_invoice = "update_acct_invoice",
    update_order = "update_order"
  }
  
  export declare enum AccountDataRetrieval {
    compare_against_cc_blacklist = "compare_against_cc_blacklist",
    get_acct_balance = "get_acct_balance",
    get_acct_comments = "get_acct_comments",
    get_acct_credit_details = "get_acct_credit_details",
    get_acct_credits = "get_acct_credits",
    get_acct_details_all = "get_acct_details_all",
    get_acct_groups_by_acct = "get_acct_groups_by_acct",
    get_acct_hierarchy_details = "get_acct_hierarchy_details",
    get_acct_multiplan_contract = "get_acct_multiplan_contract",
    get_acct_no_from_user_id = "get_acct_no_from_user_id",
    get_acct_notification_details = "get_acct_notification_details",
    get_acct_notify_method = "get_acct_notify_method",
    get_acct_open_charges = "get_acct_open_charges",
    get_acct_payment_history = "get_acct_payment_history",
    get_acct_plan_contract = "get_acct_plan_contract",
    get_acct_plan_unit_instance_all = "get_acct_plan_unit_instance_all",
    get_acct_plans = "get_acct_plans",
    get_acct_plans_all = "get_acct_plans_all",
    get_acct_supp_fields = "get_acct_supp_fields",
    get_acct_surcharges = "get_acct_surcharges",
    get_acct_trans_history = "get_acct_trans_history",
    get_acct_universal_contract = "get_acct_universal_contract",
    get_acct_uuids = "get_acct_uuids",
    get_accts_with_existing_pay_method = "get_accts_with_existing_pay_method",
    get_all_acct_contracts = "get_all_acct_contracts",
    get_aria_xml_statement = "get_aria_xml_statement",
    get_avail_child_plans_for_acct = "get_avail_child_plans_for_acct",
    get_avail_child_plans_for_acct_all = "get_avail_child_plans_for_acct_all",
    get_cc_uuid = "get_cc_uuid",
    get_cc_velocity_info = "get_cc_velocity_info",
    get_child_accts = "get_child_accts",
    get_order_items = "get_order_items",
    get_pmt_uuid = "get_pmt_uuid",
    get_queued_service_plans = "get_queued_service_plans",
    get_recurring_credit_info = "get_recurring_credit_info",
    get_standing_usage = "get_standing_usage",
    get_supp_field_values = "get_supp_field_values",
    get_unbilled_usage_summary = "get_unbilled_usage_summary",
    get_usage_history = "get_usage_history",
    get_usage_summary_by_type = "get_usage_summary_by_type",
    get_user_id_from_acct_no = "get_user_id_from_acct_no",
    get_userid_has_ordered_sku = "get_userid_has_ordered_sku",
    update_cc_blacklist = "update_cc_blacklist",
    userid_exists = "userid_exists",
    userid_is_available = "userid_is_available"
  }
  
  export declare enum AccountModification {
    adjust_billing_dates = "adjust_billing_dates",
    assign_collections_acct_group = "assign_collections_acct_group",
    assign_functional_acct_group = "assign_functional_acct_group",
    assign_supp_plan = "assign_supp_plan",
    assign_supp_plan_multi = "assign_supp_plan_multi",
    ban_acct = "ban_acct",
    cancel_acct_plan_contract = "cancel_acct_plan_contract",
    cancel_supp_plan = "cancel_supp_plan",
    close_acct_installation = "close_acct_installation",
    copy_acct_payment_method = "copy_acct_payment_method",
    create_acct_multiplan_contract = "create_acct_multiplan_contract",
    create_acct_plan_contract = "create_acct_plan_contract",
    create_acct_universal_contract = "create_acct_universal_contract",
    delete_acct_coupon = "delete_acct_coupon",
    get_country_from_ip = "get_country_from_ip",
    modify_acct_multiplan_contract = "modify_acct_multiplan_contract",
    modify_acct_plan_contract = "modify_acct_plan_contract",
    modify_acct_plan_unit_instances = "modify_acct_plan_unit_instances",
    modify_acct_supp_fields = "modify_acct_supp_fields",
    modify_acct_universal_contract = "modify_acct_universal_contract",
    modify_supp_plan = "modify_supp_plan",
    remove_acct_from_group = "remove_acct_from_group",
    remove_custom_acct_rates = "remove_custom_acct_rates",
    remove_pay_method = "remove_pay_method",
    replace_supp_plan = "replace_supp_plan",
    reset_usg_mtd_bal = "reset_usg_mtd_bal",
    reset_usg_ptd_bal = "reset_usg_ptd_bal",
    send_acct_statement_email = "send_acct_statement_email",
    set_acct_notify_override = "set_acct_notify_override",
    set_acct_notify_tmplt_grp = "set_acct_notify_tmplt_grp",
    set_acct_usg_daily_threshold = "set_acct_usg_daily_threshold",
    set_acct_usg_mtd_threshold = "set_acct_usg_mtd_threshold",
    set_acct_usg_ptd_threshold = "set_acct_usg_ptd_threshold",
    set_client_usg_daily_threshold = "set_client_usg_daily_threshold",
    set_client_usg_mtd_threshold = "set_client_usg_mtd_threshold",
    set_client_usg_ptd_threshold = "set_client_usg_ptd_threshold",
    set_pay_method_bank_draft = "set_pay_method_bank_draft",
    set_pay_method_cc = "set_pay_method_cc",
    set_pay_method_net_terms = "set_pay_method_net_terms",
    set_payment_responsibility = "set_payment_responsibility",
    set_service_plan_immediately = "set_service_plan_immediately",
    update_acct_complete = "update_acct_complete",
    update_acct_contact = "update_acct_contact",
    update_acct_credentials = "update_acct_credentials",
    update_acct_notify_method = "update_acct_notify_method",
    update_acct_plan_unit_instance = "update_acct_plan_unit_instance",
    update_acct_status = "update_acct_status",
    update_acct_supp_fields = "update_acct_supp_fields",
    update_existing_billing_info = "update_existing_billing_info",
    update_payment_method = "update_payment_method"
  }
  
  export declare enum AccountCommunicationRetrieval {
    get_acct_invoice_history = "get_acct_invoice_history",
    get_acct_message = "get_acct_message",
    get_acct_message_size = "get_acct_message_size",
    get_acct_preview_statement = "get_acct_preview_statement",
    get_acct_statement_history = "get_acct_statement_history",
    get_acct_status_history = "get_acct_status_history",
    get_acct_supp_plan_history = "get_acct_supp_plan_history",
    get_statement_content = "get_statement_content",
    get_statement_content_size = "get_statement_content_size",
    get_statement_for_inv_size = "get_statement_for_inv_size",
    get_statement_for_invoice = "get_statement_for_invoice"
  }
  
  export declare enum Special {
    authenticate_caller = "authenticate_caller",
    gen_random_string = "gen_random_string",
    get_all_acct_receipt_ids = "get_all_acct_receipt_ids",
    get_all_actions_by_receipt_id = "get_all_actions_by_receipt_id",
    get_all_client_receipt_ids = "get_all_client_receipt_ids",
    set_external_object_id = "set_external_object_id",
    toggle_test_account = "toggle_test_account"
  }
  
  export declare enum ImplementationConfigurationRetrieval {
    clear_reg_uss_config_params = "clear_reg_uss_config_params",
    clear_reg_uss_params = "clear_reg_uss_params",
    client_has_event_class = "client_has_event_class",
    delete_reg_uss_config_params = "delete_reg_uss_config_params",
    delete_reg_uss_params = "delete_reg_uss_params",
    get_acct_groups_by_client = "get_acct_groups_by_client",
    get_acct_payment_methods = "get_acct_payment_methods",
    get_auf_status = "get_auf_status",
    get_avail_child_plans_for_plan = "get_avail_child_plans_for_plan",
    get_avail_child_plans_for_plan_all = "get_avail_child_plans_for_plan_all",
    get_available_plans = "get_available_plans",
    get_available_plans_all = "get_available_plans_all",
    get_child_for_item_class = "get_child_for_item_class",
    get_client_countries = "get_client_countries",
    get_client_currencies = "get_client_currencies",
    get_client_item_classes = "get_client_item_classes",
    get_client_item_images = "get_client_item_images",
    get_client_item_prices = "get_client_item_prices",
    get_client_item_supp_fields = "get_client_item_supp_fields",
    get_client_items_all = "get_client_items_all",
    get_client_items_basic = "get_client_items_basic",
    get_client_plan_service_rates = "get_client_plan_service_rates",
    get_client_plan_services = "get_client_plan_services",
    get_client_plans_all = "get_client_plans_all",
    get_client_plans_basic = "get_client_plans_basic",
    get_coupon_details = "get_coupon_details",
    get_credit_reason_codes = "get_credit_reason_codes",
    get_current_system_version = "get_current_system_version",
    get_daily_batch_status = "get_daily_batch_status",
    get_email_templates = "get_email_templates",
    get_inv_no_from_bal_xfer = "get_inv_no_from_bal_xfer",
    get_items_by_class = "get_items_by_class",
    get_items_by_supp_field = "get_items_by_supp_field",
    get_master_plans_by_supp_field = "get_master_plans_by_supp_field",
    get_parent_for_item_class = "get_parent_for_item_class",
    get_plans_by_promo_code = "get_plans_by_promo_code",
    get_plans_by_promo_code_all = "get_plans_by_promo_code_all",
    get_rate_schedules_for_plan = "get_rate_schedules_for_plan",
    get_reg_uss_config_params = "get_reg_uss_config_params",
    get_reg_uss_params = "get_reg_uss_params",
    get_supp_plans_by_promo_code = "get_supp_plans_by_promo_code",
    get_supp_plans_by_promo_code_all = "get_supp_plans_by_promo_code_all",
    get_supp_plans_by_supp_field = "get_supp_plans_by_supp_field",
    get_top_level_item_class = "get_top_level_item_class",
    get_virtual_datetime = "get_virtual_datetime",
    get_web_replacement_vals = "get_web_replacement_vals",
    pre_calc_invoice = "pre_calc_invoice",
    replace_reg_uss_config_params = "replace_reg_uss_config_params",
    replace_reg_uss_params = "replace_reg_uss_params",
    set_reg_uss_config_params = "set_reg_uss_config_params",
    set_reg_uss_params = "set_reg_uss_params",
    validate_session = "validate_session",
    record_alternative_payment = "record_alternative_payment",
    settle_account_balance_bulk = "settle_account_balance_bulk"
  }
  
  export declare enum AccountCreation {
    create_acct_complete = "create_acct_complete",
    create_acct_hierarchy = "create_acct_hierarchy"
  }
  
  export declare enum ImplementationConfigurationModification {
    advance_virtual_datetime = "advance_virtual_datetime",
    disable_all_standing_usage = "disable_all_standing_usage",
    disable_standing_usage_by_plan = "disable_standing_usage_by_plan",
    get_acct_tax_exempt_status = "get_acct_tax_exempt_status",
    keep_alive = "keep_alive",
    kill_session = "kill_session",
    set_acct_tax_exempt_status = "set_acct_tax_exempt_status",
    set_prov_engine = "set_prov_engine",
    set_session = "set_session",
    set_session_auth = "set_session_auth",
    subscribe_event = "subscribe_event",
    subscribe_event_class = "subscribe_event_class",
    subscribe_events = "subscribe_events",
    unsubscribe_event = "unsubscribe_event",
    unsubscribe_event_class = "unsubscribe_event_class",
    unsubscribe_events = "unsubscribe_events",
    update_master_plan = "update_master_plan"
  }
  
  export declare enum AccountCommunicationCreation {
    gen_statement = "gen_statement",
    get_acct_plan_history = "get_acct_plan_history",
    send_acct_email = "send_acct_email",
    send_arc_threshold_email = "send_arc_threshold_email",
    write_acct_comment = "write_acct_comment"
  }
  
  export declare enum AccountUnbilledUsageSummaryInformation {
    get_unbilled_usage_summary = "get_unbilled_usage_summary",
    reset_usg_mtd_bal = "reset_usg_mtd_bal",
    reset_usg_ptd_bal = "reset_usg_ptd_bal",
    set_acct_usg_daily_threshold = "set_acct_usg_daily_threshold",
    set_acct_usg_mtd_threshold = "set_acct_usg_mtd_threshold",
    set_acct_usg_ptd_threshold = "set_acct_usg_ptd_threshold",
    set_client_usg_daily_threshold = "set_client_usg_daily_threshold",
    set_client_usg_mtd_threshold = "set_client_usg_mtd_threshold",
    set_client_usg_ptd_threshold = "set_client_usg_ptd_threshold"
  }
}